import Layout from '../components/layout/Layout';
import '../styles/globals.css';
import Head from 'next/head';

function MyApp({ Component }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component/>
    </Layout>
  )
}

export default MyApp
